/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://a5hec2h4hjf7bhrtf6t5wkoimu.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-quks672h4nguzn2u3v2mh7hizy",
  aws_cognito_identity_pool_id:
    "us-east-1:ab9bd2f3-21c4-4c0d-a5de-a7d7bd5decff",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_k0pp2c36f",
  aws_user_pools_web_client_id: "1faq9ro642alrcg5lcon1osm4a",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL", "NAME"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: "myblogs2022192429-dev",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;
